const genres = {
  0: 'ALL',
  5: 'Latin',
  7: 'Country',
  1: 'EDM (All)',
  11: 'Afro House',
  12: 'Brazilian Bass',
  13: 'Chill House',
  14: 'Chill-step',
  15: 'Dancehall',
  16: 'Deep House',
  17: 'Downtempo',
  18: 'Dubstep',
  19: 'Electronica',
  20: 'Future Bass',
  21: 'Future House',
  22: 'Hardstyle',
  23: 'Melbourne Bounce',
  24: 'Minimal',
  25: 'Moombahton',
  26: 'Progressive House',
  27: 'Tropical House',
  28: 'Tech House',
  29: 'Trap',
  30: 'Trance/Psy-trance',
  31: 'Underground',
  32: 'Vaporwave/synthwave',
  3: 'Pop (All)',
  34: 'Commercial',
  35: 'Electro - Pop',
  36: 'Latin Pop',
  2: 'Rock/Metal (All)',
  38: 'Acoustic',
  39: 'Alternative',
  40: 'Hardcore',
  41: 'Heavy',
  42: 'Melodic',
  43: 'Post Rock',
  44: 'Pop',
  45: 'Punk',
  6: 'Indie (All)',
  47: 'Folk',
  48: 'Shoegaze',
  49: 'Singer-Songwriter',
  4: 'Urban/R&B (All)',
  60: 'Hip Hop',
  61: 'LatinX',
  62: 'Rap',
  63: 'Soul',
  65: 'Other (All)',
  51: 'Ethnic/World',
  52: 'Christian',
  53: 'Swing',
  54: 'Contemporary',
  55: 'Instrumental',
  56: 'Reggae',
  57: 'Jazz',
  58: 'International'
}

export { genres }
